#!/usr/bin/env python3
"""Validate the generated data under data/ against MODEL.md.

Three families of checks:

  schema       every event / week file has the fields MODEL.md documents,
               with the documented types
  consistency  each city's index.json agrees with its week files
               (presence, counts, window, title, newest-first order)
  stats        data/stats.json totals agree with the week files

The files here are generated by `party-scout-code` (see README.md), so some
violations pre-date this script. They are recorded as per-check counts in
scripts/validation_baseline.json and tolerated; the run fails as soon as a
check goes *above* its baseline, i.e. on any new or growing violation.

Usage:
    python3 scripts/validate_data.py                # check against the baseline
    python3 scripts/validate_data.py --strict       # ignore the baseline
    python3 scripts/validate_data.py --update-baseline
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from collections import Counter
from datetime import date, timedelta

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "data")
BASELINE = os.path.join(ROOT, "scripts", "validation_baseline.json")

DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
WINDOW_RE = re.compile(r"^(\d{4}-\d{2}-\d{2})\.\.(\d{4}-\d{2}-\d{2})$")
HHMM_RE = re.compile(r"^\d{2}:\d{2}$")
TRACKS = ("music", "sports")

# MODEL.md "## `data/<city>/<week_start>.json` — one week"
WEEK_FIELDS = {
    "week_start": str,
    "window": str,
    "title": str,
    "location": str,
    "city": str,
    "city_label": str,
    "generated_at": str,
    "tracks": dict,
}

# MODEL.md "## `<event>`" — field: (type, nullable). Required on every event.
EVENT_FIELDS = {
    "id": (str, False),
    "eid": (str, False),
    "track": (str, False),
    "category": (str, False),
    "name": (str, False),
    "day": (str, False),
    "date": (str, False),
    "time": (str, False),
    "area": (str, False),
    "venue": (str, False),
    "address": (str, False),
    "why": (str, False),
    "summary": (str, False),
    "price": (str, False),
    "tags": (list, False),
    "sources": (list, False),
    "tickets": (list, False),
    "maps": (dict, False),
    "popularity": (int, False),
    "active": (bool, False),
}
# Type-checked when present, never required:
#  - MODEL.md marks `promoter`, `lineup` and `enriched` optional (`enriched`
#    "Defaults to 0").
#  - the rest are written by a *later* pass — `geocode.py` (`coords`,
#    `coords_precise`), `enrich_images.py` (`image`, `image_generated`),
#    `derive_times` (`start`, `end`), the RA lookup (`ra`). A freshly
#    scouted event legitimately has none of them yet; how many are still
#    missing is already reported by data/stats.json's `by_field_fixable`.
EVENT_OPTIONAL = {
    "promoter": (str, False),
    "lineup": (list, False),
    "enriched": (int, False),
    "start": (str, True),
    "end": (str, True),
    "coords": (dict, True),
    "coords_precise": (bool, False),
    "ra": (dict, False),
    "image": (str, False),
    "image_generated": (bool, False),
}
# MODEL.md documents `""` as a legitimate value for these; the rest of the
# string fields' emptiness is a *quality* metric already tracked by
# data/stats.json's `by_field_fixable`, not a schema error. Only the fields
# that identify or place an event are required to be non-empty here.
NON_EMPTY = ("id", "eid", "track", "name", "area")


class Report:
    """Collects violations keyed by check code."""

    def __init__(self) -> None:
        self.counts: Counter = Counter()
        self.samples: dict = {}

    def add(self, code: str, where: str, detail: str = "") -> None:
        self.counts[code] += 1
        self.samples.setdefault(code, [])
        if len(self.samples[code]) < 8:
            self.samples[code].append(f"{where}{': ' + detail if detail else ''}")


def load_json(path: str, rep: Report):
    try:
        with open(path, encoding="utf-8") as fh:
            return json.load(fh)
    except (OSError, ValueError) as exc:
        rep.add("json-parse", rel(path), str(exc))
        return None


def rel(path: str) -> str:
    return os.path.relpath(path, ROOT)


def type_name(value) -> str:
    return "null" if value is None else type(value).__name__


def parse_date(value: str):
    """A real calendar date, or None — `2026-02-30` matches DATE_RE but isn't one."""
    try:
        return date.fromisoformat(value)
    except ValueError:
        return None


def check_type(rep: Report, code: str, where: str, field: str, value, spec) -> bool:
    expected, nullable = spec
    if value is None:
        if not nullable:
            rep.add(code, where, f"{field} is null")
            return False
        return True
    # bool is a subclass of int — keep `popularity: true` from passing.
    if expected is int and isinstance(value, bool):
        rep.add(code, where, f"{field} is bool, want int")
        return False
    if not isinstance(value, expected):
        rep.add(code, where, f"{field} is {type_name(value)}, want {expected.__name__}")
        return False
    return True


def check_event(rep: Report, where: str, event, track_key: str, window) -> None:
    if not isinstance(event, dict):
        rep.add("event-not-object", where, type_name(event))
        return

    for field, spec in EVENT_FIELDS.items():
        if field not in event:
            rep.add("event-missing-field", where, field)
            continue
        check_type(rep, "event-field-type", where, field, event[field], spec)
    for field, spec in EVENT_OPTIONAL.items():
        if field in event:
            check_type(rep, "event-field-type", where, field, event[field], spec)

    unknown = sorted(set(event) - set(EVENT_FIELDS) - set(EVENT_OPTIONAL))
    for field in unknown:
        rep.add("event-unknown-field", where, field)

    for field in NON_EMPTY:
        value = event.get(field)
        if isinstance(value, str) and not value.strip():
            rep.add("event-empty-field", where, field)

    if isinstance(event.get("track"), str):
        if event["track"] not in TRACKS:
            rep.add("event-bad-track", where, event["track"])
        elif event["track"] != track_key:
            rep.add("event-track-mismatch", where, f"{event['track']} under tracks.{track_key}")

    day = event.get("date")
    if isinstance(day, str) and day:
        if not DATE_RE.match(day) or parse_date(day) is None:
            rep.add("event-date-format", where, day)
        elif window and not (window[0] <= day <= window[1]):
            rep.add("event-date-outside-window", where, f"{day} not in {window[0]}..{window[1]}")

    for field in ("start", "end"):
        value = event.get(field)
        if isinstance(value, str) and not HHMM_RE.match(value):
            rep.add("event-time-format", where, f"{field}={value!r}")

    maps = event.get("maps")
    if isinstance(maps, dict) and maps and not {"google", "apple"} <= set(maps):
        rep.add("event-maps-keys", where, ",".join(sorted(maps)))

    coords = event.get("coords")
    if isinstance(coords, dict) and coords and not {"lat", "lon"} <= set(coords):
        rep.add("event-coords-keys", where, ",".join(sorted(coords)))

    lineup = event.get("lineup")
    if isinstance(lineup, list):
        for artist in lineup:
            if not isinstance(artist, dict):
                rep.add("event-lineup-shape", where, f"{type_name(artist)} entry")
            elif not isinstance(artist.get("name"), str):
                rep.add("event-lineup-shape", where, f"name is {type_name(artist.get('name'))}")

    popularity = event.get("popularity")
    if isinstance(popularity, int) and not isinstance(popularity, bool):
        if not 0 <= popularity <= 10:
            rep.add("event-popularity-range", where, str(popularity))

    enriched = event.get("enriched")
    if isinstance(enriched, int) and not isinstance(enriched, bool) and enriched < 0:
        rep.add("event-enriched-range", where, str(enriched))


def check_week_file(rep: Report, path: str, city: str, city_label) -> dict | None:
    """Validate one data/<city>/<week_start>.json. Returns it when parseable."""
    week = load_json(path, rep)
    where = rel(path)
    if week is None:
        return None
    if not isinstance(week, dict):
        rep.add("week-not-object", where, type_name(week))
        return None

    for field, expected in WEEK_FIELDS.items():
        if field not in week:
            rep.add("week-missing-field", where, field)
        elif not isinstance(week[field], expected):
            rep.add("week-field-type", where, f"{field} is {type_name(week[field])}")

    stem = os.path.basename(path)[: -len(".json")]
    week_start = week.get("week_start")
    monday = None
    if isinstance(week_start, str):
        if week_start != stem:
            rep.add("week-filename-mismatch", where, f"week_start={week_start}")
        elif not DATE_RE.match(week_start) or parse_date(week_start) is None:
            rep.add("week-start-format", where, week_start)
        else:
            monday = parse_date(week_start)
            if monday.weekday() != 0:
                rep.add("week-start-not-monday", where, week_start)

    window = None
    raw_window = week.get("window")
    if isinstance(raw_window, str):
        match = WINDOW_RE.match(raw_window)
        if not match:
            rep.add("week-window-format", where, raw_window)
        else:
            window = (match.group(1), match.group(2))
            if parse_date(window[0]) is None or parse_date(window[1]) is None:
                rep.add("week-window-format", where, raw_window)
                window = None
            elif window[0] > window[1]:
                rep.add("week-window-reversed", where, raw_window)
            elif monday is not None:
                last = (monday + timedelta(days=6)).isoformat()
                if not (week_start <= window[0] and window[1] <= last):
                    rep.add("week-window-outside-week", where, f"{raw_window} vs {week_start}..{last}")

    if week.get("city") != city:
        rep.add("week-city-mismatch", where, f"city={week.get('city')!r}, want {city!r}")
    if city_label is not None and week.get("city_label") != city_label:
        rep.add("week-city-label-mismatch", where, f"city_label={week.get('city_label')!r}, want {city_label!r}")

    tracks = week.get("tracks")
    if not isinstance(tracks, dict):
        return week
    ids: Counter = Counter()
    eids: Counter = Counter()
    for track_key in sorted(tracks):
        events = tracks[track_key]
        if track_key not in TRACKS:
            rep.add("week-unknown-track", where, track_key)
        if not isinstance(events, list):
            rep.add("week-track-type", where, f"tracks.{track_key} is {type_name(events)}")
            continue
        for i, event in enumerate(events):
            check_event(rep, f"{where} tracks.{track_key}[{i}]", event, track_key, window)
            if isinstance(event, dict):
                for field, seen in (("id", ids), ("eid", eids)):
                    if isinstance(event.get(field), str) and event[field]:
                        seen[event[field]] += 1
    for field, seen in (("id", ids), ("eid", eids)):
        for value, n in sorted(seen.items()):
            if n > 1:
                rep.add(f"event-duplicate-{field}", where, f"{value} x{n}")
    return week


def check_index(rep: Report, city: str, weeks_on_disk: dict) -> None:
    """data/<city>/index.json vs that city's week files (MODEL.md § index.json)."""
    path = os.path.join(DATA, city, "index.json")
    where = rel(path)
    if not os.path.exists(path):
        rep.add("index-missing", where)
        return
    index = load_json(path, rep)
    if index is None:
        return
    entries = index.get("weeks") if isinstance(index, dict) else None
    if not isinstance(entries, list):
        rep.add("index-shape", where, "weeks is not a list")
        return

    listed = []
    for i, entry in enumerate(entries):
        at = f"{where} weeks[{i}]"
        if not isinstance(entry, dict):
            rep.add("index-entry-shape", at, type_name(entry))
            continue
        week_start = entry.get("week_start")
        if not isinstance(week_start, str) or not DATE_RE.match(week_start):
            rep.add("index-entry-shape", at, f"week_start={week_start!r}")
            continue
        listed.append(week_start)
        for field in ("window", "title"):
            if not isinstance(entry.get(field), str):
                rep.add("index-entry-shape", at, f"{field}={entry.get(field)!r}")
        counts = entry.get("counts")
        if not isinstance(counts, dict):
            rep.add("index-entry-shape", at, f"counts={type_name(counts)}")
            counts = None

        week = weeks_on_disk.get(week_start)
        if week is None:
            rep.add("index-extra-week", at, f"{week_start}.json is missing")
            continue
        if counts is not None:
            tracks = week.get("tracks") if isinstance(week, dict) else None
            if isinstance(tracks, dict):
                actual = {k: len(v) for k, v in tracks.items() if isinstance(v, list)}
                if actual != counts:
                    rep.add("index-count-mismatch", at, f"{week_start}: index {counts} vs file {actual}")
        for field in ("window", "title"):
            if isinstance(entry.get(field), str) and entry[field] != week.get(field):
                rep.add(f"index-{field}-mismatch", at, f"{week_start}: {entry[field]!r} vs {week.get(field)!r}")

    for week_start in sorted(set(weeks_on_disk) - set(listed)):
        rep.add("index-missing-week", where, f"{week_start}.json is not listed")
    for week_start, n in sorted(Counter(listed).items()):
        if n > 1:
            rep.add("index-duplicate-week", where, f"{week_start} x{n}")
    if listed != sorted(listed, reverse=True):
        rep.add("index-order", where, "weeks are not newest-first")


def check_stats(rep: Report, per_city: dict) -> None:
    """data/stats.json totals vs the week files."""
    path = os.path.join(DATA, "stats.json")
    where = rel(path)
    if not os.path.exists(path):
        rep.add("stats-missing", where)
        return
    stats = load_json(path, rep)
    if not isinstance(stats, dict):
        return

    actual_total = sum(sum(c.values()) for c in per_city.values())
    actual_weeks = sum(len(c) for c in per_city.values())
    total = stats.get("total")
    if not isinstance(total, dict):
        rep.add("stats-shape", where, f"total={type_name(total)}")
    else:
        for field, actual in (("n", actual_total), ("weeks_published", actual_weeks), ("cities", len(per_city))):
            if total.get(field) != actual:
                rep.add(f"stats-total-{field}", where, f"total.{field}={total.get(field)} vs {actual}")

    cities = stats.get("cities")
    if not isinstance(cities, list):
        rep.add("stats-shape", where, f"cities={type_name(cities)}")
        return
    seen = set()
    for i, entry in enumerate(cities):
        at = f"{where} cities[{i}]"
        if not isinstance(entry, dict) or not isinstance(entry.get("city"), str):
            rep.add("stats-shape", at, "city entry")
            continue
        city = entry["city"]
        seen.add(city)
        weeks = per_city.get(city)
        if weeks is None:
            rep.add("stats-unknown-city", at, city)
            continue
        if entry.get("n") != sum(weeks.values()):
            rep.add("stats-city-n", at, f"{city}: {entry.get('n')} vs {sum(weeks.values())}")
        if entry.get("weeks_published") != len(weeks):
            rep.add("stats-city-weeks", at, f"{city}: {entry.get('weeks_published')} vs {len(weeks)}")
        if isinstance(entry.get("weeks"), list):
            for j, week in enumerate(entry["weeks"]):
                if not isinstance(week, dict) or week.get("week_start") not in weeks:
                    rep.add("stats-week-unknown", f"{at} weeks[{j}]", str(week.get("week_start") if isinstance(week, dict) else week))
                elif week.get("n") != weeks[week["week_start"]]:
                    rep.add("stats-week-n", f"{at} weeks[{j}]", f"{week['week_start']}: {week.get('n')} vs {weeks[week['week_start']]}")
    for city in sorted(set(per_city) - seen):
        rep.add("stats-missing-city", where, city)


def check_cities(rep: Report) -> dict:
    """data/cities.json vs the data/<city>/ partitions. Returns slug -> label."""
    path = os.path.join(DATA, "cities.json")
    where = rel(path)
    labels: dict = {}
    doc = load_json(path, rep) if os.path.exists(path) else None
    if doc is None:
        rep.add("cities-missing", where)
        return labels
    entries = doc.get("cities") if isinstance(doc, dict) else None
    if not isinstance(entries, list) or not entries:
        rep.add("cities-shape", where, "cities is not a non-empty list")
        return labels
    for i, entry in enumerate(entries):
        at = f"{where} cities[{i}]"
        if not isinstance(entry, dict) or not isinstance(entry.get("slug"), str) or not isinstance(entry.get("label"), str):
            rep.add("cities-shape", at, "want {slug, label} strings")
            continue
        labels[entry["slug"]] = entry["label"]
        if not os.path.isdir(os.path.join(DATA, entry["slug"])):
            rep.add("cities-missing-partition", at, entry["slug"])
    for name in sorted(os.listdir(DATA)):
        if os.path.isdir(os.path.join(DATA, name)) and name not in labels:
            rep.add("cities-unlisted-partition", where, name)
    return labels


def validate() -> Report:
    rep = Report()
    labels = check_cities(rep)
    partitions = sorted(
        name for name in os.listdir(DATA) if os.path.isdir(os.path.join(DATA, name))
    )
    per_city: dict = {}
    for city in partitions:
        weeks_on_disk = {}
        counts = {}
        for name in sorted(os.listdir(os.path.join(DATA, city))):
            if not name.endswith(".json") or name == "index.json":
                continue
            week = check_week_file(rep, os.path.join(DATA, city, name), city, labels.get(city))
            stem = name[: -len(".json")]
            if week is None:
                continue
            weeks_on_disk[stem] = week
            tracks = week.get("tracks")
            counts[stem] = (
                sum(len(v) for v in tracks.values() if isinstance(v, list))
                if isinstance(tracks, dict)
                else 0
            )
        per_city[city] = counts
        check_index(rep, city, weeks_on_disk)
    check_stats(rep, per_city)
    return rep


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--baseline", default=BASELINE, help="path to the baseline file")
    parser.add_argument("--strict", action="store_true", help="fail on any violation, ignoring the baseline")
    parser.add_argument("--update-baseline", action="store_true", help="rewrite the baseline from the current data")
    args = parser.parse_args(argv)

    rep = validate()

    baseline = {}
    if not args.strict and os.path.exists(args.baseline):
        with open(args.baseline, encoding="utf-8") as fh:
            baseline = json.load(fh).get("allowed", {})

    if args.update_baseline:
        payload = {
            "_comment": (
                "Pre-existing violations tolerated by scripts/validate_data.py: "
                "max allowed count per check. Regenerate with "
                "`python3 scripts/validate_data.py --update-baseline`."
            ),
            "allowed": dict(sorted(rep.counts.items())),
            "samples": {k: v for k, v in sorted(rep.samples.items())},
        }
        with open(args.baseline, "w", encoding="utf-8") as fh:
            json.dump(payload, fh, indent=2, ensure_ascii=False)
            fh.write("\n")
        print(f"wrote {rel(args.baseline)} with {sum(rep.counts.values())} tolerated violations")
        return 0

    regressions = []
    improvements = []
    for code in sorted(set(rep.counts) | set(baseline)):
        found, allowed = rep.counts.get(code, 0), baseline.get(code, 0)
        if found > allowed:
            regressions.append((code, found, allowed))
        elif found < allowed:
            improvements.append((code, found, allowed))

    if rep.counts:
        print("violations found:")
        for code, found in sorted(rep.counts.items()):
            allowed = baseline.get(code, 0)
            mark = "FAIL" if found > allowed else "ok  "
            print(f"  {mark} {code}: {found} (allowed {allowed})")
            for sample in rep.samples[code]:
                print(f"         {sample}")
            if found > len(rep.samples[code]):
                print(f"         ... and {found - len(rep.samples[code])} more")
    else:
        print("no violations found")

    if improvements:
        print("\nbelow baseline (run --update-baseline to lock the improvement in):")
        for code, found, allowed in improvements:
            print(f"  {code}: {found} < {allowed}")

    if regressions:
        print("\nFAILED — these checks are above their baseline:")
        for code, found, allowed in regressions:
            print(f"  {code}: {found} > {allowed}")
        print(
            "\nThe data under data/ is generated by party-scout-code (see README.md) —\n"
            "fix the generator rather than hand-editing the files. If the increase is\n"
            "genuinely acceptable, re-bless it with:\n"
            "  python3 scripts/validate_data.py --update-baseline"
        )
        return 1

    print("\nOK — no new or growing violations.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
